package com.nombrenegocio.pc211834u20221a132.billing.domain.model.aggregates;

import com.nombrenegocio.pc211834u20221a132.billing.domain.model.valueobjects.BillingPeriod;
import com.nombrenegocio.pc211834u20221a132.billing.domain.model.valueobjects.CustomerId;
import com.nombrenegocio.pc211834u20221a132.billing.domain.model.valueobjects.MonetaryAmount;
import com.nombrenegocio.pc211834u20221a132.billing.domain.model.valueobjects.InvoiceStatus;
import com.nombrenegocio.pc211834u20221a132.billing.domain.model.valueobjects.NombreProyectoIdentifier;
import com.nombrenegocio.pc211834u20221a132.shared.domain.model.aggregates.AbstractDomainAggregateRoot;
import lombok.Getter;
import lombok.Setter;

@Getter
public class Invoice extends AbstractDomainAggregateRoot<Invoice> {

    /**
     * The technical identifier for the invoice. Autogenerated primary key.
     */
    @Setter
    private Long id;
    /**
     * The externally generated identifier that uniquely identifies this invoice document.
     */
    @Setter
    private NombreProyectoIdentifier invoiceIdentifier;
    /**
     * The identifier of the customer this invoice is billed to.
     */
    @Setter
    private CustomerId customerId;
    /**
     * The period of time this invoice covers.
     */
    @Setter
    private BillingPeriod billingPeriod;
    /**
     * The total monetary amount of the invoice.
     */
    @Setter
    private MonetaryAmount totalAmount;
    /**
     * The current status of the invoice.
     */
    @Setter
    private InvoiceStatus status;
    /**
     * An optional free-text note about the invoice.
     */
    @Setter
    private String memo;

    /**
     * Default constructor required by the persistence/assembler layer.
     */
    public Invoice() {
    }

    /**
     * Full constructor for Invoice.
     *
     * @param invoiceIdentifier The externally generated invoice identifier.
     * @param customerId        The identifier of the billed customer.
     * @param billingPeriod     The period covered by this invoice.
     * @param totalAmount       The total amount due.
     * @param status            The current status of the invoice.
     * @param memo              An optional note. May be null.
     */
    public Invoice(NombreProyectoIdentifier invoiceIdentifier,
                   CustomerId customerId,
                   BillingPeriod billingPeriod,
                   MonetaryAmount totalAmount,
                   InvoiceStatus status,
                   String memo) {
        this.invoiceIdentifier = invoiceIdentifier;
        this.customerId = customerId;
        this.billingPeriod = billingPeriod;
        this.totalAmount = totalAmount;
        this.status = status;
        this.memo = memo;
    }

    /**
     * Factory method used by the application layer to create a valid Invoice aggregate.
     *
     * @param invoiceIdentifier The externally generated invoice identifier.
     * @param customerId        The identifier of the billed customer.
     * @param billingPeriod     The period covered by this invoice.
     * @param totalAmount       The total amount due.
     * @param status            The current status of the invoice.
     * @param memo              An optional note. May be null.
     * @return a new Invoice aggregate.
     */
    public static Invoice create(NombreProyectoIdentifier invoiceIdentifier,
                                 CustomerId customerId,
                                 BillingPeriod billingPeriod,
                                 MonetaryAmount totalAmount,
                                 InvoiceStatus status,
                                 String memo) {
        return new Invoice(invoiceIdentifier, customerId, billingPeriod, totalAmount, status, memo);
    }

    /**
     * Updates the status of the invoice.
     *
     * @param status The new status.
     * @return The updated Invoice instance.
     */
    public Invoice updateStatus(InvoiceStatus status) {
        this.status = status;
        return this;
    }

    /**
     * Updates the memo of the invoice.
     *
     * @param memo The new memo. May be null.
     * @return The updated Invoice instance.
     */
    public Invoice updateMemo(String memo) {
        this.memo = memo;
        return this;
    }
}
